package com.adyen.examples.hpp;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.zip.GZIPOutputStream;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.codec.binary.Base64;

/**
 * Create Payment On Hosted Payment Page (HPP)
 * 
 * The Adyen Hosted Payment Pages (HPPs) provide a flexible, secure and easy way to allow shoppers to pay for goods or
 * services. By submitting the form generated by this servlet to our HPP a payment will be created for the shopper.
 * 
 * @link /1.HPP/CreatePaymentOnHpp
 * @author Created by Adyen - Payments Made Easy
 */

@WebServlet(urlPatterns = { "/1.HPP/CreatePaymentOnHpp" })
public class CreatePaymentOnHpp extends HttpServlet {

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		/**
		 * General HPP settings
		 * - hppUrl: URL of the Adyen HPP to submit the form to
		 * - hmacKey: shared secret key used to encrypt the signature
		 * 
		 * Both variables are dependent on the environment which should be used (Test/Live).
		 * HMAC key can be set up: Adyen CA >> Skins >> Choose your Skin >> Edit Tab >> Edit HMAC key for Test & Live.
		 */
		String hppUrl = "https://test.adyen.com/hpp/pay.shtml";
		String hmacKey = "YourHmacSecretKey";

		/**
		 * Defining variables
		 * The HPP requires certain variables to be posted in order to create a payment possibility for the shopper.
		 * 
		 * The variables that you can post to the HPP are the following:
		 * 
		 * <pre>
		 * merchantReference    : The merchant reference is your reference for the payment
		 * paymentAmount        : Amount specified in minor units EUR 1,00 = 100
		 * currencyCode         : The three-letter capitalised ISO currency code to pay in i.e. EUR
		 * shipBeforeDate       : The date by which the goods or services are shipped.
		 *                        Format: YYYY-MM-DD
		 * skinCode             : The skin code that should be used for the payment
		 * merchantAccount      : The merchant account you want to process this payment with.
		 * sessionValidity      : The final time by which a payment needs to have been made. 
		 *                        Format: YYYY-MM-DDThh:mm:ssTZD
		 * shopperLocale        : A combination of language code and country code to specify 
		 *                        the language used in the session i.e. en_GB.
		 * orderData            : A fragment of HTML/text that will be displayed on the HPP (optional)
		 * countryCode          : Country code according to ISO_3166-1_alpha-2 standard  (optional)
		 * shopperEmail         : The e-mailaddress of the shopper (optional)
		 * shopperReference     : The shopper reference, i.e. the shopper ID (optional)
		 * allowedMethods       : Allowed payment methods separated with a , i.e. "ideal,mc,visa" (optional)
		 * blockedMethods       : Blocked payment methods separated with a , i.e. "ideal,mc,visa" (optional)
		 * offset               : Numeric value that will be added to the fraud score (optional)
		 * merchantSig          : The HMAC signature used by Adyen to test the validy of the form;
		 * </pre>
		 */

		// Generate dates
		Calendar calendar = Calendar.getInstance();
		Date currentDate = calendar.getTime(); // current date
		calendar.add(Calendar.DATE, 1);
		Date sessionDate = calendar.getTime(); // current date + 1 day
		calendar.add(Calendar.DATE, 2);
		Date shippingDate = calendar.getTime(); // current date + 3 days

		// Define variables
		String merchantReference = "TEST-PAYMENT-" + new SimpleDateFormat("yyyy-MM-dd-HH:mm:ss").format(currentDate);
		String paymentAmount = "199";
		String currencyCode = "EUR";
		String shipBeforeDate = new SimpleDateFormat("yyyy-MM-dd").format(shippingDate);
		String skinCode = "YourSkinCode";
		String merchantAccount = "YourMerchantAccount";
		String sessionValidity = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX").format(sessionDate);
		String shopperLocale = "en_US";
		String orderData = compressString("Orderdata to display on the HPP can be put here");
		String countryCode = "NL";
		String shopperEmail = "";
		String shopperReference = "";
		String allowedMethods = "";
		String blockedMethods = "";
		String offset = "";

		/**
		 * Signing the form
		 * 
		 * The merchant signature is used by Adyen to verify if the posted data is not altered by the shopper. The
		 * signature must be encrypted according to the procedure below.
		 * 
		 * Please note: the signature does contain more variables, in this example they are NOT required since they are
		 * empty. Please have a look at the advanced HPP example for a comprehensive overview on what should be part of
		 * the signature.
		 */

		String signingString = paymentAmount + currencyCode + shipBeforeDate + merchantReference + skinCode
				+ merchantAccount + sessionValidity + shopperEmail + shopperReference + allowedMethods + blockedMethods
				+ offset;

		String merchantSig;
		try {
			merchantSig = calculateHMAC(hmacKey, signingString);
		} catch (GeneralSecurityException e) {
			throw new ServletException(e);
		}

		// Set request parameters for use on the JSP page
		request.setAttribute("hppUrl", hppUrl);
		request.setAttribute("merchantReference", merchantReference);
		request.setAttribute("paymentAmount", paymentAmount);
		request.setAttribute("currencyCode", currencyCode);
		request.setAttribute("shipBeforeDate", shipBeforeDate);
		request.setAttribute("skinCode", skinCode);
		request.setAttribute("merchantAccount", merchantAccount);
		request.setAttribute("sessionValidity", sessionValidity);
		request.setAttribute("shopperLocale", shopperLocale);
		request.setAttribute("orderData", orderData);
		request.setAttribute("countryCode", countryCode);
		request.setAttribute("shopperEmail", shopperEmail);
		request.setAttribute("shopperReference", shopperReference);
		request.setAttribute("allowedMethods", allowedMethods);
		request.setAttribute("blockedMethods", blockedMethods);
		request.setAttribute("offset", offset);
		request.setAttribute("merchantSig", merchantSig);

		// Forward request data to corresponding JSP page
		request.getRequestDispatcher("/1.HPP/create-payment-on-hpp.jsp").forward(request, response);
	}

	/**
	 * Generates GZIP compressed and Base64 encoded string.
	 */
	private String compressString(String input) throws IOException {
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		GZIPOutputStream gzip = new GZIPOutputStream(output);

		gzip.write(input.getBytes());
		gzip.close();
		output.close();

		return Base64.encodeBase64String(output.toByteArray());
	}

	/**
	 * Computes the Base64 encoded signature using the HMAC algorithm with the SHA-1 hashing function.
	 */
	private String calculateHMAC(String hmacKey, String signingString) throws GeneralSecurityException {
		SecretKeySpec keySpec = new SecretKeySpec(hmacKey.getBytes(), "HmacSHA1");
		Mac mac = Mac.getInstance("HmacSHA1");
		mac.init(keySpec);

		byte[] result = mac.doFinal(signingString.getBytes());
		return Base64.encodeBase64String(result);
	}

}
