package com.adyen.examples.payout;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.ws.BindingProvider;

import com.adyen.services.common.Amount;
import com.adyen.services.payment.Recurring;
import com.adyen.services.payout.PayoutPortType;
import com.adyen.services.payout.PayoutService;
import com.adyen.services.payout.SubmitRequest;
import com.adyen.services.payout.SubmitResponse2;

/**
 * Submit Payout Request (SOAP)
 * 
 * You can submit a Payout payment using a specific recurringDetails record, or by using the last created
 * recurringDetails record. This example shows how you can perform such a request using SOAP.
 * 
 * Please note: the Payout functionality is set up as a 2-step process. Because of this there are two additional
 * Webservice User accounts needed to use the Payout process. Please request the Payout permission for a specific user
 * account with Adyen Support. The password can be set in Adyen CA >> Settings >> Users.
 * 
 * @link /9.Payout/Soap/SubmitPayoutRequest
 * @author Created by Adyen - Payments Made Easy
 */

@WebServlet(urlPatterns = { "/9.Payout/Soap/SubmitPayoutRequest" })
public class SubmitPayoutRequest extends HttpServlet {

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		/**
		 * SOAP settings
		 * - wsdl: the WSDL url you are using (Test/Live)
		 * - wsUser: your web service user to store Payout details, and to initiate a Payout
		 * - wsPassword: your web service user's password
		 */
		String wsdl = "https://pal-test.adyen.com/pal/servlet/soap/Payout?wsdl";
		String wsUser = "YourWSUser";
		String wsPassword = "YourWSPassword";

		/**
		 * Create SOAP client, using classes in adyen-wsdl-cxf.jar library (generated by wsdl2java tool, Apache CXF).
		 * 
		 * @see WebContent/WEB-INF/lib/adyen-wsdl-cxf.jar
		 */
		PayoutService service = new PayoutService(new URL(wsdl));
		PayoutPortType client = service.getPayoutHttpPort();

		// Set HTTP Authentication
		((BindingProvider) client).getRequestContext().put(BindingProvider.USERNAME_PROPERTY, wsUser);
		((BindingProvider) client).getRequestContext().put(BindingProvider.PASSWORD_PROPERTY, wsPassword);

		/**
		 * Initiate a Payout request is done by calling the submit action on the Payout Service with a submit request.
		 * The submit request has the following fields:
		 * 
		 * <pre>
		 * - recurring
		 *     - contract       : The contract value of the recurring object should be present and contain value PAYOUT.
		 * - selectedRecurringDetailReference: This is the recurringDetailReference you want to use for this payment.
		 *                        You can use the value LATEST to select the most recently used recurring detail.
		 * - merchantAccount    : The merchant account you want to process this payout with.
		 * - amount
		 *     - currencyCode   : The three character ISO currency code.
		 *     - value          : The payout amount in minor units (e.g. EUR 1,00 = 100).
		 * - reference          : The (merchant) reference for this payout. This reference will be used in all
		 *                        communication to the merchant about the status of the payout and the created payment
		 *                        (after confirmation of the payout).
		 *                        Although it is a good idea to make sure it is unique, this is not a requirement.
		 * - shopperEmail       : The email address of the shopper. This does not have to match the email address supplied
		 *                        with the initial payment/store details since it may have changed in the mean time.
		 * - shopperReference   : The reference to the shopper. This must be the same as the shopperReference used in 
		 *                        the initial payment and/or store details call.
		 * - shopperStatement   : The description of this payout. This description is shown on the bank statement of
		 *                        the shopper (if this is supported by the chosen payment method, optional).
		 * - fraudOffset        : A integer that is added to normal fraud score, either positive or negative (optional).
		 * </pre>
		 */

		// Create new submit request
		SubmitRequest submitRequest = new SubmitRequest();
		submitRequest.setMerchantAccount("YourMerchantAccount");
		submitRequest.setReference("TEST-PAYOUT-" + new SimpleDateFormat("yyyy-MM-dd-HH:mm:ss").format(new Date()));
		submitRequest.setShopperEmail("test@shopper.com");
		submitRequest.setShopperReference("ShopperReference");
		submitRequest.setShopperStatement("ShopperStatement");
		submitRequest.setFraudOffset(0);

		// Set recurring contract
		submitRequest.setSelectedRecurringDetailReference("LATEST");

		Recurring recurring = new Recurring();
		recurring.setContract("PAYOUT");
		submitRequest.setRecurring(recurring);

		// Set amount
		Amount amount = new Amount();
		amount.setCurrency("EUR");
		amount.setValue(1000L);
		submitRequest.setAmount(amount);

		/**
		 * Send the submit payout request.
		 */
		SubmitResponse2 submitResult = client.submit(submitRequest);

		/**
		 * If the message is syntactically valid and merchantAccount is correct you will receive a submitResponse with
		 * the following fields:
		 * 
		 * <pre>
		 * - pspReference      : A new reference to uniquely identify this Payout request.
		 * - resultCode        : In case of success, this will be [payout-submit-received] or, in case of an error,
		 *                       an informational message will be returned.
		 * - refusalReason     : In case of refusal, an informational message for the reason.
		 * </pre>
		 * 
		 * You should not expect to receive a Notification at this time as it has not yet been confirmed.
		 */
		PrintWriter out = response.getWriter();

		out.println("Submit Payout Result:");
		out.println("- pspReference: " + submitResult.getPspReference());
		out.println("- resultCode: " + submitResult.getResultCode());
		out.println("- refusalReason: " + submitResult.getRefusalReason());

	}

}
